### ISSUE TITLE
The pip package is out of date

### ISSUE THREAD

**Issue by NauticalMile64** [takaakiaoki/ofblockmeshdicthelper#3]
Although the version number of the package available through pip is equal to the current version (0.1.9), there are functions present in the head version of the repo (e.g. BlockMeshDict.add_arcedge) are not present in the stored package. I've replaced my local __init__.py with the one from the repo, but you might want to update the package on pypi.

**Comment by takaakiaoki** [comment]
Thanks for your comment.
latest package is uploaded on PyPI as version 2.0.
Please try it.

**Comment by NauticalMile64** [comment]
It's working, thanks.
